### ISSUE TITLE
impload fails on older firmware versions

### ISSUE THREAD

**Issue by stronnag** [stronnag/impload#3]
On old iNav firmware (e.g. 1.7.2), impload fails:
```
2018/11/16 08:04:08 Using device com4
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.MSPInit(0x1, 0x12440088, 0x4, 0x1c200, 0x0, 0x0, 0x0, 0x0)
         /home/jrh/Projects/impload/msp.go:267 +0xc4e
main.do_test()
         /home/jrh/Projects/impload/impload.go:45 +0x35
main.main()
         /home/jrh/Projects/impload/impload.go:191 +0x305
```

This is due to the older API, that impload fails to handle correctly.

**Comment by stronnag** [comment]
Ancient firmware does not provide the full board name, fixed by afa7570
